#!/usr/bin/env python3
"""Regenerate tests/host/inflate_vectors.h (compressed inputs for test_inflate).

Each vector's plain text comes from gen(n, seed), which test_inflate.c
reimplements, so only the compressed bytes are stored here.
"""
import gzip, io, struct, zlib, os

ALPHA = b"abc de\n<>/=\"tvgprogrammechannel"
WORDS = [b"<programme ", b"channel=\"", b"start=\"20260928", b"</title>\n", b"<desc>", b"news ", b"sport",
         b" +0000\" ", b"stop=\"", b"\">", b"<title lang=\"en\">", b"</programme>\n", b"film ", b"the ", b"and ", b"BBC"]

def gen(n, seed):
    """Word salad with some single random characters: compresses like XMLTV."""
    x, out = seed, bytearray()
    while len(out) < n:
        x = (x * 1103515245 + 12345) & 0x7FFFFFFF
        k = (x >> 16) % 20
        if k < 16:
            out += WORDS[k]
        else:
            out.append(ALPHA[(x >> 8) % len(ALPHA)])
    return bytes(out[:n])

def gz(data, level=9, name=None, mtime=0):
    b = io.BytesIO()
    with gzip.GzipFile(filename=name or "", mode="wb", compresslevel=level, fileobj=b, mtime=mtime) as f:
        f.write(data)
    return b.getvalue()

def gz_all_flags(data):
    # FTEXT|FHCRC|FEXTRA|FNAME|FCOMMENT, then a raw deflate body and trailer.
    hdr = bytearray(b"\x1f\x8b\x08\x1f\x00\x00\x00\x00\x00\x03")
    hdr += struct.pack("<H", 5) + b"extra" + b"guide.xml\x00" + b"a comment\x00"
    hdr += struct.pack("<H", zlib.crc32(bytes(hdr)) & 0xFFFF)
    c = zlib.compressobj(6, zlib.DEFLATED, -15)
    body = c.compress(data) + c.flush()
    return bytes(hdr) + body + struct.pack("<II", zlib.crc32(data), len(data) & 0xFFFFFFFF)

def zl(data, level=6, strategy=zlib.Z_DEFAULT_STRATEGY):
    c = zlib.compressobj(level, zlib.DEFLATED, 15, 9, strategy)
    return c.compress(data) + c.flush()

# (name, compressed, plain parts as (n, seed) list, expect)
V = []
a = gen(3000, 1)
V.append(("gzip_l9", gz(a), [(3000, 1)], "end"))
V.append(("gzip_l1", gz(a, 1), [(3000, 1)], "end"))
V.append(("gzip_stored", gz(a, 0), [(3000, 1)], "end"))
V.append(("gzip_flags", gz_all_flags(a), [(3000, 1)], "end"))
V.append(("zlib_fixed", zl(a, 6, zlib.Z_FIXED), [(3000, 1)], "end"))
V.append(("zlib_huffonly", zl(a, 6, zlib.Z_HUFFMAN_ONLY), [(3000, 1)], "end"))
w = gen(30000, 7)
V.append(("gzip_window", gz(w + w + gen(9000, 8)), [(30000, 7), (30000, 7), (9000, 8)], "end"))
V.append(("gzip_members", gz(gen(1000, 2)) + gz(gen(2000, 3), 1), [(1000, 2), (2000, 3)], "end"))
V.append(("gzip_empty", gz(b""), [], "end"))
V.append(("gzip_trailing_junk", gz(a) + b"\x00\x00junk", [(3000, 1)], "end"))
bad = bytearray(gz(a)); bad[-8] ^= 1
V.append(("gzip_bad_crc", bytes(bad), [(3000, 1)], "err"))
V.append(("gzip_truncated", gz(a)[:-20], [], "short"))
bad2 = bytearray(zl(a)); bad2[-1] ^= 0x40
V.append(("zlib_bad_adler", bytes(bad2), [(3000, 1)], "err"))
V.append(("plain", b"<?xml version=\"1.0\"?>\n<tv></tv>\n", [], "plain"))

out = ["// Generated by gen_inflate_vectors.py -- do not edit.", "#include <stdint.h>", ""]
out.append("typedef struct { const char *name; const uint8_t *z; int zlen; int parts[4][2]; int nparts; const char *expect; } InflVec;")
for name, z, parts, exp in V:
    out.append("static const uint8_t v_%s[%d] = {" % (name, len(z)))
    for i in range(0, len(z), 20):
        out.append("    " + ",".join("0x%02x" % b for b in z[i:i + 20]) + ",")
    out.append("};")
out.append("static const InflVec VECS[] = {")
for name, z, parts, exp in V:
    ps = ",".join("{%d,%d}" % p for p in parts) or "{0,0}"
    out.append('    { "%s", v_%s, %d, {%s}, %d, "%s" },' % (name, name, len(z), ps, len(parts), exp))
out.append("};")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "inflate_vectors.h")
open(path, "w").write("\n".join(out) + "\n")
print("wrote", path, sum(len(v[1]) for v in V), "compressed bytes")
