#!/usr/bin/env python3
"""Regenerate tests/host/logo_vectors.h (images for test_logo_image) with Pillow."""
import io, os, struct, zlib
from PIL import Image

def png_rgba():          # 320x120: left half opaque red, right half transparent; alpha-weighted edges
    im = Image.new("RGBA", (320, 120), (0, 0, 0, 0))
    for x in range(160):
        for y in range(120):
            im.putpixel((x, y), (255, 0, 0, 255))
    b = io.BytesIO(); im.save(b, "PNG"); return b.getvalue()

def jpeg(progressive=False):   # 400x400 quadrants: red, green / blue, white
    im = Image.new("RGB", (400, 400))
    for (x0, y0, c) in ((0, 0, (255, 0, 0)), (200, 0, (0, 255, 0)), (0, 200, (0, 0, 255)), (200, 200, (255, 255, 255))):
        im.paste(c, (x0, y0, x0 + 200, y0 + 200))
    b = io.BytesIO(); im.save(b, "JPEG", quality=90, progressive=progressive); return b.getvalue()

def gif():               # 40x20 palette image, green
    im = Image.new("P", (40, 20)); im.putpalette([0, 200, 0] * 256)
    b = io.BytesIO(); im.save(b, "GIF"); return b.getvalue()

def bmp():               # 30x10 blue
    b = io.BytesIO(); Image.new("RGB", (30, 10), (0, 0, 255)).save(b, "BMP"); return b.getvalue()

def png_huge_header():   # a valid-looking header for 3000x10: refused before decoding
    def chunk(t, d): return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xFFFFFFFF)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 3000, 10, 8, 6, 0, 0, 0)) + chunk(b"IEND", b"")

p = png_rgba()
V = [("png_rgba", p), ("jpeg", jpeg()), ("jpeg_prog", jpeg(True)), ("gif", gif()), ("bmp", bmp()),
     ("png_cut", p[:len(p) // 2]), ("png_huge", png_huge_header()),
     ("svg", b'<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"></svg>')]
out = ["// Generated by gen_logo_vectors.py -- do not edit.", "#include <stdint.h>", ""]
for name, d in V:
    out.append("static const uint8_t img_%s[%d] = {" % (name, len(d)))
    for i in range(0, len(d), 20): out.append("    " + ",".join("0x%02x" % c for c in d[i:i + 20]) + ",")
    out.append("};")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logo_vectors.h")
open(path, "w").write("\n".join(out) + "\n")
print("wrote", path, sum(len(d) for _, d in V), "bytes of images")
