// ca_anchors.h — root CAs for HTTPS certificate verification (BearSSL format).
// The array lives in ca_anchors.c, generated by scripts/gen-trust-anchors.py.
#ifndef PS4CAST_CA_ANCHORS_H
#define PS4CAST_CA_ANCHORS_H

#include <stddef.h>
#include "bearssl.h"

extern const br_x509_trust_anchor CA_ANCHORS[];
extern const size_t CA_ANCHORS_NUM;
extern const char CA_ANCHORS_DATE[];   // generation date (YYYY-MM-DD), shown in /status

#endif
