#!/usr/bin/env python3
"""Generate app/src/ca_anchors.c: BearSSL trust anchors for HTTPS verification.

The console has no CA store BearSSL can use, so PS4 Cast ships its own: the
Mozilla root program as packaged by `certifi`, converted into the
br_x509_trust_anchor array that BearSSL's `brssl ta` tool would emit.

Regenerate when roots are added/retired (a stale bundle slowly starts failing
sites whose CA moved to a newer root):

    python3 -m pip install --user certifi cryptography
    python3 scripts/gen-trust-anchors.py            # uses certifi's cacert.pem
    python3 scripts/gen-trust-anchors.py bundle.pem # or any PEM bundle
    python3 scripts/gen-trust-anchors.py bundle.pem -o out.c   # other output

Roots with key types BearSSL cannot verify (e.g. Ed25519) are skipped and
listed on stderr.
"""
import datetime
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "app" / "src" / "ca_anchors.c"

CURVES = {  # BearSSL curve ids (bearssl_ec.h)
    "secp256r1": "BR_EC_secp256r1",
    "secp384r1": "BR_EC_secp384r1",
    "secp521r1": "BR_EC_secp521r1",
}


def c_bytes(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 16):
        rows.append("\t" + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]))
    return f"static const unsigned char {name}[] = {{\n" + ",\n".join(rows) + "\n};\n"


def int_bytes(v: int) -> bytes:
    return v.to_bytes((v.bit_length() + 7) // 8 or 1, "big")


def main() -> int:
    args = sys.argv[1:]
    out_path = OUT
    if "-o" in args:
        i = args.index("-o")
        out_path = Path(args[i + 1]).resolve()
        del args[i:i + 2]
    if args:
        src = Path(args[0])
        label = src.name
    else:
        import certifi
        src = Path(certifi.where())
        label = f"certifi {certifi.__version__}"
    certs = x509.load_pem_x509_certificates(src.read_bytes())

    decls, entries, skipped, seen = [], [], [], set()
    for cert in certs:
        subject = cert.subject.rfc4514_string()
        key = cert.public_key()
        dn = cert.subject.public_bytes()
        n = len(entries)
        if isinstance(key, rsa.RSAPublicKey):
            nums = key.public_numbers()
            ident = ("rsa", dn, nums.n)
            if ident in seen:
                continue
            decls.append(c_bytes(f"TA{n}_DN", dn))
            decls.append(c_bytes(f"TA{n}_RSA_N", int_bytes(nums.n)))
            decls.append(c_bytes(f"TA{n}_RSA_E", int_bytes(nums.e)))
            pkey = (f"{{ BR_KEYTYPE_RSA, {{ .rsa = {{ (unsigned char *)TA{n}_RSA_N, sizeof TA{n}_RSA_N, "
                    f"(unsigned char *)TA{n}_RSA_E, sizeof TA{n}_RSA_E }} }} }}")
        elif isinstance(key, ec.EllipticCurvePublicKey) and key.curve.name in CURVES:
            q = key.public_bytes(serialization.Encoding.X962,
                                 serialization.PublicFormat.UncompressedPoint)
            ident = ("ec", dn, q)
            if ident in seen:
                continue
            decls.append(c_bytes(f"TA{n}_DN", dn))
            decls.append(c_bytes(f"TA{n}_EC_Q", q))
            pkey = (f"{{ BR_KEYTYPE_EC, {{ .ec = {{ {CURVES[key.curve.name]}, "
                    f"(unsigned char *)TA{n}_EC_Q, sizeof TA{n}_EC_Q }} }} }}")
        else:
            skipped.append(subject)
            continue
        seen.add(ident)
        expires = cert.not_valid_after_utc.date().isoformat()
        entries.append(f"\t/* {subject.replace('*/', '*_/')} (until {expires}) */\n"
                       f"\t{{ {{ (unsigned char *)TA{n}_DN, sizeof TA{n}_DN }}, BR_X509_TA_CA, {pkey} }}")

    today = datetime.date.today().isoformat()
    out = [
        "// Generated by scripts/gen-trust-anchors.py -- do not edit by hand.\n",
        f"// Source: {label}; {len(entries)} anchors; generated {today}.\n",
        "// Regenerate periodically: see the script's header.\n",
        '#include "ca_anchors.h"\n\n',
        *decls,
        "\nconst br_x509_trust_anchor CA_ANCHORS[] = {\n",
        ",\n".join(entries),
        "\n};\n\n",
        f"const size_t CA_ANCHORS_NUM = {len(entries)};\n",
        f'const char CA_ANCHORS_DATE[] = "{today}";\n',
    ]
    out_path.write_text("".join(out))
    for s in skipped:
        print(f"skipped (unsupported key type): {s}", file=sys.stderr)
    print(f"{out_path}: {len(entries)} anchors from {label}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
